// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"

	"github.com/scality/static-oci-registry/pkg/domain"
	"github.com/scality/static-oci-registry/pkg/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLayoutWalker creates a new instance of MockLayoutWalker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLayoutWalker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLayoutWalker {
	mock := &MockLayoutWalker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLayoutWalker is an autogenerated mock type for the LayoutWalker type
type MockLayoutWalker struct {
	mock.Mock
}

type MockLayoutWalker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLayoutWalker) EXPECT() *MockLayoutWalker_Expecter {
	return &MockLayoutWalker_Expecter{mock: &_m.Mock}
}

// WalkLayouts provides a mock function for the type MockLayoutWalker
func (_mock *MockLayoutWalker) WalkLayouts(ctx context.Context, imageName domain.ImageName) iter.Seq2[service.Layout, error] {
	ret := _mock.Called(ctx, imageName)

	if len(ret) == 0 {
		panic("no return value specified for WalkLayouts")
	}

	var r0 iter.Seq2[service.Layout, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName) iter.Seq2[service.Layout, error]); ok {
		r0 = returnFunc(ctx, imageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[service.Layout, error])
		}
	}
	return r0
}

// MockLayoutWalker_WalkLayouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalkLayouts'
type MockLayoutWalker_WalkLayouts_Call struct {
	*mock.Call
}

// WalkLayouts is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
func (_e *MockLayoutWalker_Expecter) WalkLayouts(ctx any, imageName any) *MockLayoutWalker_WalkLayouts_Call {
	return &MockLayoutWalker_WalkLayouts_Call{Call: _e.mock.On("WalkLayouts", ctx, imageName)}
}

func (_c *MockLayoutWalker_WalkLayouts_Call) Run(run func(ctx context.Context, imageName domain.ImageName)) *MockLayoutWalker_WalkLayouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLayoutWalker_WalkLayouts_Call) Return(seq2 iter.Seq2[service.Layout, error]) *MockLayoutWalker_WalkLayouts_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockLayoutWalker_WalkLayouts_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName) iter.Seq2[service.Layout, error]) *MockLayoutWalker_WalkLayouts_Call {
	_c.Call.Return(run)
	return _c
}
