// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLayout creates a new instance of MockLayout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLayout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLayout {
	mock := &MockLayout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLayout is an autogenerated mock type for the Layout type
type MockLayout struct {
	mock.Mock
}

type MockLayout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLayout) EXPECT() *MockLayout_Expecter {
	return &MockLayout_Expecter{mock: &_m.Mock}
}

// Location provides a mock function for the type MockLayout
func (_mock *MockLayout) Location() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Location")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLayout_Location_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Location'
type MockLayout_Location_Call struct {
	*mock.Call
}

// Location is a helper method to define mock.On call
func (_e *MockLayout_Expecter) Location() *MockLayout_Location_Call {
	return &MockLayout_Location_Call{Call: _e.mock.On("Location")}
}

func (_c *MockLayout_Location_Call) Run(run func()) *MockLayout_Location_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLayout_Location_Call) Return(s string) *MockLayout_Location_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLayout_Location_Call) RunAndReturn(run func() string) *MockLayout_Location_Call {
	_c.Call.Return(run)
	return _c
}

// OpenBlob provides a mock function for the type MockLayout
func (_mock *MockLayout) OpenBlob(ctx context.Context, digest domain.Digest) (io.ReadSeekCloser, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for OpenBlob")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Digest) (io.ReadSeekCloser, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Digest) io.ReadSeekCloser); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Digest) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayout_OpenBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenBlob'
type MockLayout_OpenBlob_Call struct {
	*mock.Call
}

// OpenBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - digest domain.Digest
func (_e *MockLayout_Expecter) OpenBlob(ctx any, digest any) *MockLayout_OpenBlob_Call {
	return &MockLayout_OpenBlob_Call{Call: _e.mock.On("OpenBlob", ctx, digest)}
}

func (_c *MockLayout_OpenBlob_Call) Run(run func(ctx context.Context, digest domain.Digest)) *MockLayout_OpenBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Digest
		if args[1] != nil {
			arg1 = args[1].(domain.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLayout_OpenBlob_Call) Return(readSeekCloser io.ReadSeekCloser, err error) *MockLayout_OpenBlob_Call {
	_c.Call.Return(readSeekCloser, err)
	return _c
}

func (_c *MockLayout_OpenBlob_Call) RunAndReturn(run func(ctx context.Context, digest domain.Digest) (io.ReadSeekCloser, error)) *MockLayout_OpenBlob_Call {
	_c.Call.Return(run)
	return _c
}

// ReadManifestByDigest provides a mock function for the type MockLayout
func (_mock *MockLayout) ReadManifestByDigest(ctx context.Context, digest domain.Digest) (*domain.FetchManifestOutput, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for ReadManifestByDigest")
	}

	var r0 *domain.FetchManifestOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Digest) (*domain.FetchManifestOutput, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Digest) *domain.FetchManifestOutput); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FetchManifestOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Digest) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayout_ReadManifestByDigest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadManifestByDigest'
type MockLayout_ReadManifestByDigest_Call struct {
	*mock.Call
}

// ReadManifestByDigest is a helper method to define mock.On call
//   - ctx context.Context
//   - digest domain.Digest
func (_e *MockLayout_Expecter) ReadManifestByDigest(ctx any, digest any) *MockLayout_ReadManifestByDigest_Call {
	return &MockLayout_ReadManifestByDigest_Call{Call: _e.mock.On("ReadManifestByDigest", ctx, digest)}
}

func (_c *MockLayout_ReadManifestByDigest_Call) Run(run func(ctx context.Context, digest domain.Digest)) *MockLayout_ReadManifestByDigest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Digest
		if args[1] != nil {
			arg1 = args[1].(domain.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLayout_ReadManifestByDigest_Call) Return(fetchManifestOutput *domain.FetchManifestOutput, err error) *MockLayout_ReadManifestByDigest_Call {
	_c.Call.Return(fetchManifestOutput, err)
	return _c
}

func (_c *MockLayout_ReadManifestByDigest_Call) RunAndReturn(run func(ctx context.Context, digest domain.Digest) (*domain.FetchManifestOutput, error)) *MockLayout_ReadManifestByDigest_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveTag provides a mock function for the type MockLayout
func (_mock *MockLayout) ResolveTag(ctx context.Context, tag domain.Tag) (*domain.FetchManifestOutput, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for ResolveTag")
	}

	var r0 *domain.FetchManifestOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tag) (*domain.FetchManifestOutput, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tag) *domain.FetchManifestOutput); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FetchManifestOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayout_ResolveTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveTag'
type MockLayout_ResolveTag_Call struct {
	*mock.Call
}

// ResolveTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag domain.Tag
func (_e *MockLayout_Expecter) ResolveTag(ctx any, tag any) *MockLayout_ResolveTag_Call {
	return &MockLayout_ResolveTag_Call{Call: _e.mock.On("ResolveTag", ctx, tag)}
}

func (_c *MockLayout_ResolveTag_Call) Run(run func(ctx context.Context, tag domain.Tag)) *MockLayout_ResolveTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Tag
		if args[1] != nil {
			arg1 = args[1].(domain.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLayout_ResolveTag_Call) Return(fetchManifestOutput *domain.FetchManifestOutput, err error) *MockLayout_ResolveTag_Call {
	_c.Call.Return(fetchManifestOutput, err)
	return _c
}

func (_c *MockLayout_ResolveTag_Call) RunAndReturn(run func(ctx context.Context, tag domain.Tag) (*domain.FetchManifestOutput, error)) *MockLayout_ResolveTag_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function for the type MockLayout
func (_mock *MockLayout) Tags(ctx context.Context) ([]domain.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 []domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLayout_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type MockLayout_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLayout_Expecter) Tags(ctx any) *MockLayout_Tags_Call {
	return &MockLayout_Tags_Call{Call: _e.mock.On("Tags", ctx)}
}

func (_c *MockLayout_Tags_Call) Run(run func(ctx context.Context)) *MockLayout_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLayout_Tags_Call) Return(tags []domain.Tag, err error) *MockLayout_Tags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockLayout_Tags_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Tag, error)) *MockLayout_Tags_Call {
	_c.Call.Return(run)
	return _c
}
