// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageFinder creates a new instance of MockImageFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageFinder {
	mock := &MockImageFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageFinder is an autogenerated mock type for the ImageFinder type
type MockImageFinder struct {
	mock.Mock
}

type MockImageFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageFinder) EXPECT() *MockImageFinder_Expecter {
	return &MockImageFinder_Expecter{mock: &_m.Mock}
}

// FindImage provides a mock function for the type MockImageFinder
func (_mock *MockImageFinder) FindImage(ctx context.Context, imageName domain.ImageName) ([]domain.SolutionVersion, error) {
	ret := _mock.Called(ctx, imageName)

	if len(ret) == 0 {
		panic("no return value specified for FindImage")
	}

	var r0 []domain.SolutionVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName) ([]domain.SolutionVersion, error)); ok {
		return returnFunc(ctx, imageName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName) []domain.SolutionVersion); ok {
		r0 = returnFunc(ctx, imageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SolutionVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ImageName) error); ok {
		r1 = returnFunc(ctx, imageName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageFinder_FindImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindImage'
type MockImageFinder_FindImage_Call struct {
	*mock.Call
}

// FindImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
func (_e *MockImageFinder_Expecter) FindImage(ctx any, imageName any) *MockImageFinder_FindImage_Call {
	return &MockImageFinder_FindImage_Call{Call: _e.mock.On("FindImage", ctx, imageName)}
}

func (_c *MockImageFinder_FindImage_Call) Run(run func(ctx context.Context, imageName domain.ImageName)) *MockImageFinder_FindImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageFinder_FindImage_Call) Return(solutionVersions []domain.SolutionVersion, err error) *MockImageFinder_FindImage_Call {
	_c.Call.Return(solutionVersions, err)
	return _c
}

func (_c *MockImageFinder_FindImage_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName) ([]domain.SolutionVersion, error)) *MockImageFinder_FindImage_Call {
	_c.Call.Return(run)
	return _c
}
