// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagLister creates a new instance of MockTagLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagLister {
	mock := &MockTagLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagLister is an autogenerated mock type for the TagLister type
type MockTagLister struct {
	mock.Mock
}

type MockTagLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagLister) EXPECT() *MockTagLister_Expecter {
	return &MockTagLister_Expecter{mock: &_m.Mock}
}

// ListTags provides a mock function for the type MockTagLister
func (_mock *MockTagLister) ListTags(ctx context.Context, imageName domain.ImageName) (*domain.ListTagsOutput, error) {
	ret := _mock.Called(ctx, imageName)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 *domain.ListTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName) (*domain.ListTagsOutput, error)); ok {
		return returnFunc(ctx, imageName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName) *domain.ListTagsOutput); ok {
		r0 = returnFunc(ctx, imageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListTagsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ImageName) error); ok {
		r1 = returnFunc(ctx, imageName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagLister_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockTagLister_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
func (_e *MockTagLister_Expecter) ListTags(ctx any, imageName any) *MockTagLister_ListTags_Call {
	return &MockTagLister_ListTags_Call{Call: _e.mock.On("ListTags", ctx, imageName)}
}

func (_c *MockTagLister_ListTags_Call) Run(run func(ctx context.Context, imageName domain.ImageName)) *MockTagLister_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagLister_ListTags_Call) Return(listTagsOutput *domain.ListTagsOutput, err error) *MockTagLister_ListTags_Call {
	_c.Call.Return(listTagsOutput, err)
	return _c
}

func (_c *MockTagLister_ListTags_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName) (*domain.ListTagsOutput, error)) *MockTagLister_ListTags_Call {
	_c.Call.Return(run)
	return _c
}
