// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagManifestFetcher creates a new instance of MockTagManifestFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagManifestFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagManifestFetcher {
	mock := &MockTagManifestFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagManifestFetcher is an autogenerated mock type for the TagManifestFetcher type
type MockTagManifestFetcher struct {
	mock.Mock
}

type MockTagManifestFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagManifestFetcher) EXPECT() *MockTagManifestFetcher_Expecter {
	return &MockTagManifestFetcher_Expecter{mock: &_m.Mock}
}

// FetchManifest provides a mock function for the type MockTagManifestFetcher
func (_mock *MockTagManifestFetcher) FetchManifest(ctx context.Context, imageName domain.ImageName, tag domain.Tag) (*domain.FetchManifestOutput, error) {
	ret := _mock.Called(ctx, imageName, tag)

	if len(ret) == 0 {
		panic("no return value specified for FetchManifest")
	}

	var r0 *domain.FetchManifestOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Tag) (*domain.FetchManifestOutput, error)); ok {
		return returnFunc(ctx, imageName, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Tag) *domain.FetchManifestOutput); ok {
		r0 = returnFunc(ctx, imageName, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FetchManifestOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ImageName, domain.Tag) error); ok {
		r1 = returnFunc(ctx, imageName, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagManifestFetcher_FetchManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchManifest'
type MockTagManifestFetcher_FetchManifest_Call struct {
	*mock.Call
}

// FetchManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
//   - tag domain.Tag
func (_e *MockTagManifestFetcher_Expecter) FetchManifest(ctx any, imageName any, tag any) *MockTagManifestFetcher_FetchManifest_Call {
	return &MockTagManifestFetcher_FetchManifest_Call{Call: _e.mock.On("FetchManifest", ctx, imageName, tag)}
}

func (_c *MockTagManifestFetcher_FetchManifest_Call) Run(run func(ctx context.Context, imageName domain.ImageName, tag domain.Tag)) *MockTagManifestFetcher_FetchManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		var arg2 domain.Tag
		if args[2] != nil {
			arg2 = args[2].(domain.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagManifestFetcher_FetchManifest_Call) Return(fetchManifestOutput *domain.FetchManifestOutput, err error) *MockTagManifestFetcher_FetchManifest_Call {
	_c.Call.Return(fetchManifestOutput, err)
	return _c
}

func (_c *MockTagManifestFetcher_FetchManifest_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName, tag domain.Tag) (*domain.FetchManifestOutput, error)) *MockTagManifestFetcher_FetchManifest_Call {
	_c.Call.Return(run)
	return _c
}
