// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDigestManifestFetcher creates a new instance of MockDigestManifestFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDigestManifestFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDigestManifestFetcher {
	mock := &MockDigestManifestFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDigestManifestFetcher is an autogenerated mock type for the DigestManifestFetcher type
type MockDigestManifestFetcher struct {
	mock.Mock
}

type MockDigestManifestFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDigestManifestFetcher) EXPECT() *MockDigestManifestFetcher_Expecter {
	return &MockDigestManifestFetcher_Expecter{mock: &_m.Mock}
}

// FetchManifest provides a mock function for the type MockDigestManifestFetcher
func (_mock *MockDigestManifestFetcher) FetchManifest(ctx context.Context, imageName domain.ImageName, digest domain.Digest) (*domain.FetchManifestOutput, error) {
	ret := _mock.Called(ctx, imageName, digest)

	if len(ret) == 0 {
		panic("no return value specified for FetchManifest")
	}

	var r0 *domain.FetchManifestOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Digest) (*domain.FetchManifestOutput, error)); ok {
		return returnFunc(ctx, imageName, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Digest) *domain.FetchManifestOutput); ok {
		r0 = returnFunc(ctx, imageName, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FetchManifestOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ImageName, domain.Digest) error); ok {
		r1 = returnFunc(ctx, imageName, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDigestManifestFetcher_FetchManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchManifest'
type MockDigestManifestFetcher_FetchManifest_Call struct {
	*mock.Call
}

// FetchManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
//   - digest domain.Digest
func (_e *MockDigestManifestFetcher_Expecter) FetchManifest(ctx any, imageName any, digest any) *MockDigestManifestFetcher_FetchManifest_Call {
	return &MockDigestManifestFetcher_FetchManifest_Call{Call: _e.mock.On("FetchManifest", ctx, imageName, digest)}
}

func (_c *MockDigestManifestFetcher_FetchManifest_Call) Run(run func(ctx context.Context, imageName domain.ImageName, digest domain.Digest)) *MockDigestManifestFetcher_FetchManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		var arg2 domain.Digest
		if args[2] != nil {
			arg2 = args[2].(domain.Digest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDigestManifestFetcher_FetchManifest_Call) Return(fetchManifestOutput *domain.FetchManifestOutput, err error) *MockDigestManifestFetcher_FetchManifest_Call {
	_c.Call.Return(fetchManifestOutput, err)
	return _c
}

func (_c *MockDigestManifestFetcher_FetchManifest_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName, digest domain.Digest) (*domain.FetchManifestOutput, error)) *MockDigestManifestFetcher_FetchManifest_Call {
	_c.Call.Return(run)
	return _c
}
