// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/scality/static-oci-registry/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobPuller creates a new instance of MockBlobPuller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobPuller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobPuller {
	mock := &MockBlobPuller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobPuller is an autogenerated mock type for the BlobPuller type
type MockBlobPuller struct {
	mock.Mock
}

type MockBlobPuller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobPuller) EXPECT() *MockBlobPuller_Expecter {
	return &MockBlobPuller_Expecter{mock: &_m.Mock}
}

// PullBlob provides a mock function for the type MockBlobPuller
func (_mock *MockBlobPuller) PullBlob(ctx context.Context, imageName domain.ImageName, digest domain.Digest) (io.ReadSeekCloser, error) {
	ret := _mock.Called(ctx, imageName, digest)

	if len(ret) == 0 {
		panic("no return value specified for PullBlob")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Digest) (io.ReadSeekCloser, error)); ok {
		return returnFunc(ctx, imageName, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ImageName, domain.Digest) io.ReadSeekCloser); ok {
		r0 = returnFunc(ctx, imageName, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ImageName, domain.Digest) error); ok {
		r1 = returnFunc(ctx, imageName, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobPuller_PullBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullBlob'
type MockBlobPuller_PullBlob_Call struct {
	*mock.Call
}

// PullBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName domain.ImageName
//   - digest domain.Digest
func (_e *MockBlobPuller_Expecter) PullBlob(ctx any, imageName any, digest any) *MockBlobPuller_PullBlob_Call {
	return &MockBlobPuller_PullBlob_Call{Call: _e.mock.On("PullBlob", ctx, imageName, digest)}
}

func (_c *MockBlobPuller_PullBlob_Call) Run(run func(ctx context.Context, imageName domain.ImageName, digest domain.Digest)) *MockBlobPuller_PullBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ImageName
		if args[1] != nil {
			arg1 = args[1].(domain.ImageName)
		}
		var arg2 domain.Digest
		if args[2] != nil {
			arg2 = args[2].(domain.Digest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlobPuller_PullBlob_Call) Return(readSeekCloser io.ReadSeekCloser, err error) *MockBlobPuller_PullBlob_Call {
	_c.Call.Return(readSeekCloser, err)
	return _c
}

func (_c *MockBlobPuller_PullBlob_Call) RunAndReturn(run func(ctx context.Context, imageName domain.ImageName, digest domain.Digest) (io.ReadSeekCloser, error)) *MockBlobPuller_PullBlob_Call {
	_c.Call.Return(run)
	return _c
}
