name: 'Setup GO Environment'
description: 'Configure GO, GOPATH, and install ginkgo'

runs:
  using: "composite"
  steps:

  - name: Set up Go
    uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
    with:
      go-version-file: go.mod

  - name: Download Go modules
    shell: bash
    run: go mod download

  - name: Verify Go modules
    shell: bash
    run: go mod verify

  - name: Install Ginkgo
    shell: bash
    run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

  - name: Add GOPATH/bin to PATH
    shell: bash
    run: echo "${GOPATH:-$HOME/go}/bin" >> $GITHUB_PATH
