name: "Pre Merge"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.24"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      is-development: true
      is-latest: false
      is-stable: false

  go-generate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Ensure go generate as been run if needed
        # We run go generate and then check if there are any changes
        run: |
          go generate ./... &&
          git diff --quiet

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  test-unit:
    uses: ./.github/workflows/test-unit.yaml
    secrets: inherit

  test-integration:
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  test-conformance:
    needs: build
    uses: ./.github/workflows/test-conformance.yaml
    secrets: inherit
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
