name: Kube tests

on:
  workflow_call:

jobs:
  kube-test:
    name: Run on Ubuntu
    runs-on: ubuntu-24.04
    steps:
      - name: clone the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: set up go
        uses: ./.github/actions/setup-go
      - name: Run Tests
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/kube-results
          make kube-test JUNIT_REPORT_DIR=${{ github.workspace }}/artifacts/kube-results
      - name: Generate HTML report
        if: always()
        run: |
          python3 -m pip install junit2html --quiet
          junit2html \
            ${{ github.workspace }}/artifacts/kube-results/junit-kube.xml \
            ${{ github.workspace }}/artifacts/kube-results/report.html
      - name: Upload test results
        if: always()
        uses: scality/action-artifacts@b311c0a0d8017683148906bd3fbe0e681b115608 # 4.3.0
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: ${{ github.workspace }}/artifacts/
