name: Integration tests

on:
  workflow_call:

jobs:
  integration-test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: set up go
        uses: ./.github/actions/setup-go
      - name: Run Tests
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/integration-results
          make integration-test JUNIT_REPORT_DIR=${{ github.workspace }}/artifacts/integration-results
      - name: Generate HTML report
        if: always()
        run: |
          python3 -m pip install junit2html --quiet
          junit2html \
            ${{ github.workspace }}/artifacts/integration-results/junit-integration.xml \
            ${{ github.workspace }}/artifacts/integration-results/report.html
      - name: Upload test results
        if: always()
        uses: scality/action-artifacts@4d348ec54efb29b5fc6226e433a1e0302242594f # v4
        with:
          method: upload
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: ${{ github.workspace }}/artifacts/
